# Sample Subscription with GraphQL

# Subscription to subscribe to notification stream of CustomerEvents
type Subscription {
    customerEvents: CustomerEvent
}

# Optionally use a union of different events to return...
#union CustomerEvent = CustomerCreatedEvent | CustomerUpdatedEvent

type CustomerEvent {
    id: ID!
    action: Action
}

enum Action {
    CREATED
    UPDATED
    DELETED
}